CREATE TABLE Movie (
	id		INTEGER NOT NULL,
	title		VARCHAR(100) NOT NULL,
	year		INTEGER NOT NULL,
	rating		VARCHAR(10),
	company		VARCHAR(50),
	PRIMARY KEY(id)) ENGINE=INNODB;

CREATE TABLE Actor (
	id		INTEGER NOT NULL,
	last		VARCHAR(20) NOT NULL,
	first		VARCHAR(20) NOT NULL,
	sex		VARCHAR(6) NOT NULL,
	dob		DATE NOT NULL,
	dod		DATE,
	PRIMARY KEY(id)) ENGINE=INNODB;

CREATE TABLE Director (
	id		INTEGER NOT NULL,
	last		VARCHAR(20) NOT NULL,
	first		VARCHAR(20) NOT NULL,
	dob		DATE NOT NULL,
	dod		DATE,
	PRIMARY KEY(id)) ENGINE=INNODB;

CREATE TABLE MovieGenre (
	mid		INTEGER NOT NULL,
	genre		VARCHAR(20) NOT NULL,
	PRIMARY KEY(mid),
	FOREIGN KEY(mid) references Movie(id)
		ON DELETE CASCADE
		ON UPDATE CASCADE
	) ENGINE=INNODB;

CREATE TABLE MovieDirector (
	mid		INTEGER NOT NULL,
	did		INTEGER NOT NULL,
	PRIMARY KEY(mid, did),
	FOREIGN KEY(mid) references Movie(id)
		ON DELETE CASCADE
		ON UPDATE CASCADE,
	FOREIGN KEY(did) references Director(id)
		ON DELETE CASCADE
		ON UPDATE CASCADE
	) ENGINE=INNODB;

CREATE TABLE MovieActor (
	mid		INTEGER NOT NULL,
	aid		INTEGER NOT NULL,
	role		VARCHAR(50),
	PRIMARY KEY(mid, aid),
	FOREIGN KEY(mid) references Movie(id)
		ON DELETE CASCADE
		ON UPDATE CASCADE,
	FOREIGN KEY(aid) references Actor(id)
		ON DELETE CASCADE
		ON UPDATE CASCADE
	) ENGINE=INNODB;

CREATE TABLE Review (
	name		VARCHAR(20) NOT NULL,
	time		TIMESTAMP NOT NULL,
	mid		INTEGER NOT NULL,
	rating		INTEGER NOT NULL CHECK(0 <= rating AND rating <= 5),
	comment		VARCHAR(500),
	PRIMARY KEY(name, mid),
	FOREIGN KEY(mid) references Movie(id)
		ON DELETE CASCADE
		ON UPDATE CASCADE
	) ENGINE = INNODB;

CREATE TABLE MaxPersonID (
	id		INTEGER NOT NULL CHECK(0 <= id));

CREATE TABLE MaxMovieID (
	id		INTEGER NOT NULL CHECK(0 <= id));
