CREATE TABLE Movie (
	id INT NOT NULL,
	title VARCHAR(100) NOT NULL,
	year INT,
	rating VARCHAR(100),
	company VARCHAR(100),
	PRIMARY KEY(id)
) ENGINE=INNODB;

CREATE TABLE Actor (
	id INT NOT NULL,
	last VARCHAR(20) NOT NULL,
	first VARCHAR(20) NOT NULL,
	sex VARCHAR(6) NOT NULL,
	dob DATE NOT NULL,
	dod DATE,
	PRIMARY KEY(id),
	CHECK(dod = NULL OR dod > dob),
	CHECK(sex = 'Female' OR sex = 'Male')
) ENGINE=INNODB;

CREATE TABLE Director (
	id INT NOT NULL,
	last VARCHAR(20) NOT NULL,
	first VARCHAR(20) NOT NULL,
	dob DATE NOT NULL,
	dod DATE,
	PRIMARY KEY(id),
	CHECK(dod = NULL OR dod > dob)
) ENGINE=INNODB;

CREATE TABLE MovieGenre (
	mid INT NOT NULL,
	genre VARCHAR(20),
	FOREIGN KEY (mid) REFERENCES Movie (id)
) ENGINE=INNODB;

CREATE TABLE MovieDirector (
	mid INT NOT NULL,
	did INT NOT NULL,
	FOREIGN KEY (mid) REFERENCES Movie (id),
	FOREIGN KEY (did) REFERENCES Director (id)
) ENGINE=INNODB;

CREATE TABLE MovieActor (
	mid INT NOT NULL,
	aid INT NOT NULL,
	role VARCHAR(50),
	FOREIGN KEY (mid) REFERENCES Movie (id),
	FOREIGN KEY (aid) REFERENCES Actor (id)
) ENGINE=INNODB;

CREATE TABLE Review (
	name VARCHAR(20),
	time TIMESTAMP,
	mid INT,
	rating INT,
	comment VARCHAR(500),
	FOREIGN KEY (mid) REFERENCES Movie (id),
	CHECK(rating >= 0 AND rating <= 5)
) ENGINE=INNODB;

CREATE TABLE MaxPersonID (
	id INT NOT NULL
) ENGINE=INNODB;

CREATE TABLE MaxMovieID (
	id INT NOT NULL
) ENGINE=INNODB;
